# Generated by Django 2.2 on 2020-05-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0001_initial_add_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('salutationCode', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('countryCode', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('orderItemId', models.CharField(max_length=255)),
                ('orderId', models.CharField(max_length=255)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('latestDeliveryDate', models.DateTimeField(auto_now=True)),
                ('ean', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('offerPrice', models.IntegerField()),
                ('offerCondition', models.CharField(max_length=255)),
                ('fulfilmentMethod', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('transportId', models.IntegerField(db_index=True)),
                ('transporterCode', models.CharField(max_length=255)),
                ('trackAndTrace', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='expiry_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('shipmentId', models.IntegerField(db_index=True)),
                ('shipmentDate', models.DateTimeField()),
                ('pickUpPoint', models.BooleanField(default=True)),
                ('customerDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol.Customer')),
                ('shipmentItems', models.ManyToManyField(related_name='items', to='bol.ShipmentItem')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bol.Transport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
