# Generated by Django 2.2 on 2020-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0002_add_models_20200501_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
