# Generated by Django 2.2 on 2020-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0004_auto_20200502_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipmentReference',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='offerReference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
