# Generated by Django 2.2 on 2020-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0005_auto_20200503_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='expiry_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
