# Generated by Django 2.2 on 2020-05-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bol', '0006_auto_20200503_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bol.Client'),
        ),
    ]
